### ISSUE TITLE
Got error `Unsupported flag` when using arguments

### ISSUE THREAD

**Issue by barolab** [barolab/action-ansible-lint#1]
When running the action with the following configuration:

```yaml
      - name: Ansible Lint
        uses: barolab/action-ansible-lint@v0.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          filter_mode: nofilter
          reporter: github-pr-review
          level: info
          targets: ansible/**/*.yml
          args: -x 301,305 --exclude ansible/playbooks/roles/external
```

I get an error `ERROR: Unsupported flag: '-x 301,305 --exclude ansible/playbooks/roles/external'`
